# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-09-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
